[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://mvp-nu-swart-38.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/done_calls"
  to = "/done_calls.html"
  status = 200
